site_name: UrbanFootprint SPM Docs

theme: readthedocs

pages:
- User Guide: 'index.md'
- Appendix A - Data Dictionary: 'data_dictionary.md'
- Appendix B - Editable Fields by Data Layer: 'editable_fields.md'
- Appendix C - SCAG Land Use Codes: 'scag_lu_codes.md'